[package]
name = "bombini"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
aya = "0.13"
aya-log = "0.2"
bombini-common = { path = "../bombini-common", features = ["user"] }
clap = { version = "4.5", features = ["derive"] }
anyhow = "1"
bitflags = { version = "2.8.0", features = ["serde"]}
bytes = "1"
env_logger = "0.10"
lazy_static = "1.5"
libc = "0.2"
log = "0.4"
procfs = "0.16"
tokio = { version = "1.25", features = ["fs", "io-util", "macros", "rt", "rt-multi-thread", "net", "signal", "sync"] }
futures-executor = "0.3"
yaml-rust2 = "0.9"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[dev-dependencies]
nix = { version = "0.29", features = ["signal"] }
tempfile = "3"

[[bin]]
name = "bombini"
path = "src/main.rs"
