[package]
name = "xtask"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4.1", features = ["derive"] }
which = "7.0"
tar = "0.4"
flate2 = "1.1"
prost-build = "0.14.1"
