# Parameters for gtfobins detector
---
gtfobins:    # https://gtfobins.github.io/#+shell%20+SUID%20+Sudo
  - aa-exec
  - ash
  - awk
  - bash
  - busctl
  - busybox
  - cabal
  - choom
  - cpio
  - csh
  - csvtool
  - dash
  - debugfs
  - distcc
  - docker
  - ed
  - elvish
  - emacs
  - env
  - expect
  - find
  - fish
  - flock
  - gawk
  - gdb
  - genie
  - gimp
  - gtester
  - hping3
  - ionice
  - ispell
  - jjs
  - jrunscript
  - julia
  - ksh
  - ld.so
  - less
  - logsave
  - lua
  - make
  - mawk
  - minicom
  - more
  - msgfilter
  - multitime
  - nawk
  - ncftp
  - nice
  - nmap
  - node
  - nohup
  - openvpn
  - pandoc
  - perf
  - perl
  - pexec
  - pg
  - php
  - python3.10
  - rc
  - rlwrap
  - rsync
  - ruby3.0
  - run-parts
  - rview
  - rvim
  - sash
  - scanmem
  - sed
  - setarch
  - setlock
  - softlimit
  - sqlite3
  - ssh-agent
  - sshpass
  - start-stop-daemon
  - stdbuf
  - strace
  - taskset
  - tclsh
  - time
  - timeout
  - unshare
  - vagrant
  - view
  - vim
  - vimdiff
  - watch
  - wget
  - xargs
  - xdotool
  - yash
  - zsh
