# Parameters for gtfobins detector
---
# Maps section. Parameters for gtfobins maps initialization
maps:
  # Map nane
  gtfobins:    # https://gtfobins.github.io/#+shell%20+SUID%20+Sudo
    # Map entries
    - key: docker run -v /:/mnt --rm -it alpine chroot /mnt sh
      value: 1
    - key: env /bin/sh
      value: 1
    - key: find . -exec /bin/sh \; -quit
      value: 1
    - key: gdb -nx -ex !sh -ex quit # skip '!sh' for now
      value: 1
    - key: perf stat /bin/sh
      value: 1
    - key: strace -o /dev/null /bin/sh
      value: 1
    - key: taskset 1 /bin/sh
      value: 1
    - key: unshare /bin/sh
      value: 1
    - key: xargs -a /dev/null sh
      value: 1
