// This file is @generated by prost-build.
/// Configuration file for ProcMon detector
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcMonConfig {
    /// Flag for exporting events from kernel to user mode.
    #[prost(bool, tag = "1")]
    #[serde(rename = "expose-events")]
    pub expose_events: bool,
    /// Process Filter Configuration.
    #[prost(message, optional, tag = "2")]
    pub process_filter: ::core::option::Option<ProcessFilter>,
}
/// Filter Events using process information.
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcessFilter {
    #[prost(oneof = "process_filter::FilterType", tags = "1, 2")]
    #[serde(flatten)]
    pub filter_type: ::core::option::Option<process_filter::FilterType>,
}
/// Nested message and enum types in `ProcessFilter`.
pub mod process_filter {
    #[derive(serde::Deserialize)]
    #[serde(untagged)]
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum FilterType {
        /// Filtering mode using allow list.
        #[prost(message, tag = "1")]
        #[serde(rename = "allow-list")]
        AllowList(super::ProcessFilterData),
        /// Filtering mode using black list.
        #[prost(message, tag = "2")]
        #[serde(rename = "deny-list")]
        DenyList(super::ProcessFilterData),
    }
}
/// Filtering parameters for process event.
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ProcessFilterData {
    /// List of UID's to filter.
    #[prost(uint32, repeated, tag = "1")]
    pub uid: ::prost::alloc::vec::Vec<u32>,
    /// List of EUID's to filter.
    #[prost(uint32, repeated, tag = "2")]
    pub euid: ::prost::alloc::vec::Vec<u32>,
    /// List of AUID's (login uid) to filter.
    #[prost(uint32, repeated, tag = "3")]
    pub auid: ::prost::alloc::vec::Vec<u32>,
    /// List of executables names to filter.
    #[prost(string, repeated, tag = "4")]
    pub binary_name: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// List of full executable paths to filter.
    #[prost(string, repeated, tag = "5")]
    pub binary_path: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// List of executable path prefixes to filter.
    #[prost(string, repeated, tag = "6")]
    pub binary_prefix: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// Configuration file for FileMon detector.
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileMonConfig {
    /// security_file_open config.
    #[prost(message, optional, tag = "1")]
    pub open: ::core::option::Option<FileHookConfig>,
    /// security_path_truncate config.
    #[prost(message, optional, tag = "2")]
    pub truncate: ::core::option::Option<FileHookConfig>,
    /// security_path_unlink config.
    #[prost(message, optional, tag = "3")]
    pub unlink: ::core::option::Option<FileHookConfig>,
    /// Filter File events by Process information.
    #[prost(message, optional, tag = "4")]
    pub process_filter: ::core::option::Option<ProcessFilter>,
}
/// FileMon hook configuration
#[derive(serde::Deserialize, Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FileHookConfig {
    /// do not load ebpf program
    #[prost(bool, tag = "1")]
    pub disable: bool,
}
/// Configuration file for NetMon detector.
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct NetMonConfig {
    /// Filter Network events by Process information.
    #[prost(message, optional, tag = "1")]
    pub process_filter: ::core::option::Option<ProcessFilter>,
}
/// Configuration file for IOUringMon detector.
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IoUringMonConfig {
    /// Filter io_uring events by Process information.
    #[prost(message, optional, tag = "1")]
    pub process_filter: ::core::option::Option<ProcessFilter>,
}
/// Configuration file for GTFOBinsDetector.
#[derive(serde::Deserialize, Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GtfoBinsConfig {
    /// Block execution of GTFOBins binaries.
    #[prost(bool, tag = "1")]
    pub enforce: bool,
    /// GTFOBins executables names.
    #[prost(string, repeated, tag = "2")]
    pub gtfobins: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
