---
name: CI
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy rustfmt
      - run: cargo binstall -y bpf-linker

      - name: Build Bombini
        run: cargo xtask build

      - name: Linting
        run: |
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check
          cd bombini-detectors-ebpf
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check
      - name: Test Bombini
        run: |
          sudo -E echo "run cargo test: " `uname -a`
          sudo -E echo "test lsm: " `cat /sys/kernel/security/lsm `
          cargo xtask test
      - name: Upload Bombini logs
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: bombini-logs
          path: /tmp/bombini-test-*
          retention-days: 5
