---
name: CI
on:
  pull_request:
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: cargo-bins/cargo-binstall@main
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: nightly
          components: clippy rustfmt
      - run: cargo binstall -y bpf-linker

      - name: Build Bombini
        run: cargo xtask build

      - name: Linting
        run: |
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check
          cd bombini-detectors-ebpf
          cargo clippy --workspace --all-features -- -D warnings
          cargo fmt --all -- --check
